---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7

# https://docs.travis-ci.com/user/languages/ruby/#bundler-20
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

notifications:
  email: false
